#!/usr/bin/python

from util import *
import argparse

parser = argparse.ArgumentParser(description='create duplicate resources')
parser.add_argument('file', metavar='file', type=str, nargs=1,
                    help='template file for creating duplicates')
parser.add_argument('replicas', metavar='', type=int, nargs=1,
                    help='number of duplicates')
parser.add_argument('interval', metavar='', type=int, nargs="?",
                    help='creation interval')
args = parser.parse_args()

filename = args.file[0]
f = open(filename, "r")
template = f.read()
f.close()

for i in range(args.replicas[0]):
    print "==============Creating %d" % i
    tmpfile = filename+".tmp"
    f = open(tmpfile, "w")
    f.write(template.replace("{}", str(i)))
    f.close()
    output = ""
    try:
        output = subprocess.check_output(KUBECTL_CREATE + tmpfile, stderr=subprocess.STDOUT, shell=True)
    except subprocess.CalledProcessError as err:
        print "Failed" + err.output
    finally:
        print output
    os.remove(tmpfile)




