#!/usr/bin/python

from util import *
import argparse

parser = argparse.ArgumentParser(description='gssh into one of the host')
parser.add_argument('host', metavar='host', type=str, nargs="?",
                    help='host to gssh')

args = parser.parse_args()

instance = get_target_gce_instance(args.host)

gcloud_compute_ssh(instance.zone, instance.name)
