#!/usr/bin/python

from util import *
import argparse

parser = argparse.ArgumentParser(description='gssh into one of the host')
parser.add_argument('host', metavar='host', type=str, nargs="?",
                    help='host to gssh')

args = parser.parse_args()
host = args.host
zone = 'us-central1-b'

if host == None:
    instances = get_all_gce_instances()
    i = input("Enter an instance index: ")
    host = instances[i].name
    zone = instances[i].zone

gcloud_compute_ssh(zone, host)