#!/usr/bin/python

import argparse
import util

parser = argparse.ArgumentParser(description='kubectl exec in pods that matches prefix')
parser.add_argument("--all", dest='all', action='store_true',
                    help='exec in all matched pods')
parser.add_argument('pod_prefix', metavar='PodPrefix', type=str, nargs=1,
                    help='prefix of pod')
parser.set_defaults(all=False)

# unkonw arguments will be passed to kubectl
args, unknown_args = parser.parse_known_args()
pod_prefix = args.pod_prefix[0]

pods = util.get_all_pods()
matched_pods = util.find_all_pods_with_prefix(pods, pod_prefix)

if len(matched_pods) <= 0:
    print("Could not find pod with prefix %s" % pod_prefix)
    exit(1)

if args.all:
    for pod in matched_pods:
        util.exec_in_pod(pod, unknown_args)
else:
    util.exec_in_pod(matched_pods[0], unknown_args)
