#!/usr/bin/python

import argparse
import util

parser = argparse.ArgumentParser(description='kubectl exec in one of the selected pods')
parser.add_argument('pod_prefix', metavar='[pod prefix]', type=str, nargs=1,
                    help='prefix of pod')
parser.add_argument('command', metavar='Command', type=str, nargs="+",
                    help='command to execute')

args = parser.parse_args()
pod_prefix = args.pod_prefix[0]

pods = util.get_all_pods()
pods = util.find_all_pods_with_prefix(pods, pod_prefix)

if len(pods) == 0:
    print("Could not find pod with prefix %s" % pod_prefix)
    exit(1)

for pod in pods:
    util.exec_in_pod(pod, args.command)
