#!/usr/bin/python

from util import *
import argparse
import os

kubelet_bin_path = search_binary_in_k8s_output_path('kubelet')

parser = argparse.ArgumentParser(description='kubectl exec in one of the ')
parser.add_argument('host', metavar='host', type=str, nargs="?",
                    help='host to gssh')

args = parser.parse_args()
host = args.host
zone = 'us-central1-b'

if host == None:
    instances = get_all_gce_instances()
    i = input("Enter an instance index: ")
    host = instances[i].name
    zone = instances[i].zone

gcloud_compute_copy_file_to_host(host, kubelet_bin_path)

cmd = """sudo bash -c '
(service kubelet status > /dev/null && service kubelet stop) || (systemctl status kubelet > /dev/null && systemctl stop kubelet)
rm /home/kubernetes/bin/kubelet || rm /usr/local/bin/kubelet
mv ./kubelet /home/kubernetes/bin/kubelet || mv ./kubelet /usr/local/bin/kubelet
sleep 5
service kubelet start || (systemctl start kubelet && echo startup)
'
"""
gcloud_compute_ssh_command(zone, host, cmd)
