#!/usr/bin/python

from util import *
import argparse
import os

parser = argparse.ArgumentParser(description='push kubelet')
parser.add_argument('host', metavar='host', type=str, nargs="?",
                    help='target host to push')

args = parser.parse_args()

kubelet_bin_path = search_binary_in_k8s_output_path('kubelet')

instance = get_target_gce_instance(args.host)

gcloud_compute_copy_file_to_host(instance.name, kubelet_bin_path)

cmd = """sudo bash -c '
(service kubelet status > /dev/null && service kubelet stop) || (systemctl status kubelet > /dev/null && systemctl stop kubelet)
rm /home/kubernetes/bin/kubelet || rm /usr/local/bin/kubelet
mv ./kubelet /home/kubernetes/bin/kubelet || mv ./kubelet /usr/local/bin/kubelet
sleep 5
service kubelet start || systemctl start kubelet && echo startup
'
"""
gcloud_compute_ssh_command(instance.zone, instance.name, cmd)
