#!/usr/bin/python

from util import *
import argparse
import os
import datetime

BASE_IMAGE = "busybox"
OUTPUT_PATH= "/tmp/my{}.tar"
COMPONENTS = ["kube-apiserver", "kube-controller-manager", "kube-scheduler"]

parser = argparse.ArgumentParser(description='push master component')
parser.add_argument("--skip-build", dest='build', action='store_false',
                    help='build kube-proxy image')
parser.add_argument('component', metavar='COMPONENT', type=str, nargs=1,
                    choices=COMPONENTS,
                    help='{ %s }' % " | ".join(COMPONENTS))
parser.add_argument('host', metavar='host', type=str, nargs="?",
                    help='target host to push')
parser.set_defaults(build=True)

args = parser.parse_args()

binary = args.component[0]
bin_path = search_binary_in_k8s_output_path(binary)
tarball_path = OUTPUT_PATH.format(binary)

if args.build:
    print "============= Build kube-proxy image tarball ================"
    tag = "my" + binary + ":" + datetime.datetime.now().strftime("%Y%m%d%H%M")
    build_kube_image(BASE_IMAGE, bin_path, binary, tag=tag)
    build_kube_image_tarball(tag, output_path=tarball_path)
    docker_rmi(tag)
else:
    tag = retrieve_image_tag(tarball_path)


print "===================Pushing %s ===================" % binary
cmd = """sudo bash -c '
docker load < my{}.tar
ls -al ~/{}.manifest > /dev/null 2>&1 || cp /etc/kubernetes/manifests/{}.manifest /home/kubernetes/{}.manifest
sed -i "s/\\"image\\":.*/\\"image\\": \\"{}\\",/" /etc/kubernetes/manifests/{}.manifest
'
"""
cmd = cmd.format(binary, binary, binary, binary, tag, binary)
instance = get_target_gce_instance(args.host)
gcloud_compute_copy_file_to_host(instance.name, tarball_path)
gcloud_compute_ssh_command(instance.zone, instance.name, cmd)

