apiVersion: v1
kind: Service
metadata:
  name: hostnamesvc-{$}
  labels:
    run: hostname-{$}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 9376
  selector:
    run: hostname

