apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: global-service
  name: global-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: global-service
  template:
    metadata:
      labels:
        run: global-service
    spec:
      containers:
      - image: gcr.io/google_containers/serve-hostname-amd64:1.5
        imagePullPolicy: IfNotPresent
        name: hostname
        readinessProbe:
          failureThreshold: 3
          httpGet:
           path: /readiness
           port: 9376
           scheme: HTTP
        ports:
        - containerPort: 9376

---
apiVersion: v1
kind: Service
metadata:
  name: global-service
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    # io.cilium/global-service: "true"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    run: global-service
  sessionAffinity: None
  type: ClusterIP
