apiVersion: v1
kind: Service
metadata:
  name: hostnamesvc-{}
  labels:
    run: hostname-{}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 9376
  selector:
    run: hostname-{}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hostname-{}
  name: hostname-{}
spec:
  selector:
    matchLabels:
      run: hostname-{}
  replicas: 2
  template:
    metadata:
      labels:
        run: hostname-{}
    spec:
      containers:
      - image: gcr.io/google_containers/serve-hostname-amd64:1.5
        imagePullPolicy: IfNotPresent
        name: hostname
        ports:
        - containerPort: 9376

