apiVersion: v1
kind: Service
metadata:
  name: hostnamesvc-{}
  labels:
    run: hostname
spec:
   #type: LoadBalancer
  # loadBalancerIP: 104.154.108.230
  ports:
  - name: http
    port: 80
    targetPort: 9376
  selector:
    run: hostname 
