apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hostname
  name: hostname
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hostname
    spec:
      containers:
      - image: gcr.io/google_containers/serve-hostname-amd64:1.5
        imagePullPolicy: IfNotPresent
        name: hostname
        readinessProbe:
          failureThreshold: 3
          httpGet:
           path: /readiness
           port: namedport
           scheme: HTTP
        ports:
        - name: namedport
          containerPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: hostname
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  ports:
   -port: 80
    protocol: TCP
    targetPort: namedport
  - port: 8080
    targetPort: 9376
  selector:
    run: hostname
  sessionAffinity: None

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hostname
spec:
  backend:
    # Re-use echoheadersx as the default backend so we stay under the default
    # quota for gce BackendServices.
    serviceName: hostname
    servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: hostname
  name: hostname1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: hostname
    spec:
      containers:
      - image: gcr.io/google_containers/serve-hostname-amd64:1.5
        imagePullPolicy: IfNotPresent
        name: hostname
        ports:
        - name: namedport
          containerPort: 8888