apiVersion: v1
kind: Service
metadata:
  name: foo-backend-neg
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    run: foo-backend
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: bar-backend-neg
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    run: bar-backend
  sessionAffinity: None
  type: ClusterIP