apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  backend:
    serviceName: foo-backend-neg
    servicePort: 80
  rules:
  - http:
      paths:
      - path: /foo
        backend:
          serviceName: foo-backend-neg
          servicePort: http
      - path: /bar
        backend:
          serviceName: bar-backend-neg
          servicePort: 80
  - host: foo.com
    http: 
      paths:
      - backend:
          serviceName: foo-backend-neg
          servicePort: 80

